### ISSUE TITLE
DMA notifier fails if using hugepages and  GB of guest memory

### ISSUE THREAD

**Issue by tmakatos** [nutanix/muser#30]
When using hugepages and 3 GB of guest memory, QEMU fails as follows:
```
qemu-system-x86_64: -device vfio-pci,sysfsdev=/sys/bus/mdev/devices/00000000-0000-0000-0000-000000000000: vfio 00000000-0000-0000-0000-000000000000: error getting device from group 0: Inappropriate ioctl for device
Verify all devices in group 0 are bound to vfio-<bus> or pci-stub and not already in use
```
The kernel emits the following warning:
```
[ 2484.634813] notifier failed for iova=100000 vaddr=7f50a3700000 size=bff00000
```

As kun.qiu@intel.com mentioned this might be because of the `kmalloc` in `muser_iommu_dma_map`. If this is the case then it should be trivial to fix e.g. by using `vmalloc`.

**Comment by tmakatos** [comment]
@raphael-nutanix FYI.

**Comment by flyfox141** [comment]
Since `kmalloc` cannot assign memory larger than 128KB, I changed `kmalloc` to `kvmalloc` in `get_dma_map` and `kfree` to `kvfree` in `put_dma_map` seems solve the problem.

**Comment by tmakatos** [comment]
> Since `kmalloc` cannot assign memory larger than 128KB, I changed `kmalloc` to `kvmalloc` in `get_dma_map` and `kfree` to `kvfree` in `put_dma_map` seems solve the problem.

Great, would you mind sending a pull request with the fix?
