### ISSUE TITLE
DMA unmap notification miss after QEMU shutdowns/fails may occur unmap errors

### ISSUE THREAD

**Issue by flyfox141** [nutanix/muser#31]
QEMU does not send any dma unmap notification when it shutdowns/fails, it may occur errors when we quit QEMU first then quit the userspace program which uses libmuser.

Generally, QEMU will notify libmuser dma map/unmap events and libmuser will maintenance the mapping table. However, if the QEMU process was ended, QEMU does not send any dma unmap notification when it shutdowns, which makes the mapping table in the libmuser still exists. 
In `dma.c`, libmuser will unmap all mapped regions by `dma_controller_destroy` if the userspace program quit. If the QEMU process does not exist, the unmap may fail since it unmap a region that does not exist.  We can see tons of kernel bug in `dmesg` when this situation occurs.

I think we need to do some cleaning if QEMU fails. Please fix me if there is anything inappropriate.

**Comment by tmakatos** [comment]
I tried reproducing this but failed to do so, are you using huge pages? Could you provide repro steps?

**Comment by tmakatos** [comment]
Closing issue as we haven't heard back from reporter.
