### ISSUE TITLE
failed to open /dev/vfio/0: No such file or directory

### ISSUE THREAD

**Issue by yuvalk** [nutanix/muser#53]
using libvirt on centos7
selinux disabled
tried to manually modify permissions on /dev/vfio/0
of course compiled and loaded all needed modules.
and running the gpio sample

all am getting is:
2020-06-18T10:35:37.783291Z qemu-kvm: -device vfio-pci,sysfsdev=/sys/bus/mdev/devices/00000000-0000-0000-0000-000000000000: vfio 00000000-0000-0000-0000-000000000000: failed to open /dev/vfio/0: No such file or directory

**Comment by yuvalk** [comment]
device is missing from lspci

**Comment by tmakatos** [comment]
Does `/sys/bus/mdev/devices/00000000-0000-0000-0000-000000000000` exist on the host? What does `dmesg` say?

**Comment by yuvalk** [comment]
````
[ 3919.365423] vfio_mdev 00000000-0000-0000-0000-000000000000: Adding to iommu group 0
[ 3919.365424] vfio_mdev 00000000-0000-0000-0000-000000000000: MDEV: group_id = 0
[ 3919.365772] muser muser: muser_create_dev: new device 00000000-0000-0000-0000-000000000000
```

```
$ ls -l /sys/bus/mdev/devices/00000000-0000-0000-0000-000000000000/
total 0
lrwxrwxrwx. 1 root root    0 Jun 18 13:53 driver -> ../../../../../bus/mdev/drivers/vfio_mdev
lrwxrwxrwx. 1 root root    0 Jun 18 13:53 iommu_group -> ../../../../../kernel/iommu_groups/0
lrwxrwxrwx. 1 root root    0 Jun 18 13:53 mdev_type -> ../mdev_supported_types/muser-1
drwxr-xr-x. 2 root root    0 Jun 18 13:53 power
--w-------. 1 root root 4096 Jun 18 13:53 remove
lrwxrwxrwx. 1 root root    0 Jun 18 13:53 subsystem -> ../../../../../bus/mdev
-rw-r--r--. 1 root root 4096 Jun 18 13:53 uevent
```

**Comment by tmakatos** [comment]
I had lots of problems trying to run QEMU on CentOS because of SELinux/cgroups etc. As what user is QEMU running?

**Comment by yuvalk** [comment]
running as qemu, and as I wrote, selinux is disabled.
oh and am using libvirt (and not qemu directly)

**Comment by tmakatos** [comment]
To check whether it's a general access issue, can you try passing a dummy but existent and readable/writable device to QEMU under `/dev`? E.g. `/dev/foo/bar`?

**Comment by tmakatos** [comment]
Also, can you `strace` QEMU to see whether it's actually `/sys/bus/mdev/devices/00000000-0000-0000-0000-000000000000` it can't access or something else?

**Comment by tmakatos** [comment]
It might be that QEMU can't access the parent directories, so best check permissions of those as well (both for `/dev/vfio/...` and for `/sys/bus/...`).

**Comment by yuvalk** [comment]
solved.

This is not related to selinux, but to libvirt cgroups.
just for reference, I was missing the following in my /etc/libvirt/qemu.conf:
```
cgroup_device_acl = [
    "/dev/null", "/dev/full", "/dev/zero",
    "/dev/random", "/dev/urandom",
    "/dev/ptmx", "/dev/kvm",
    "/dev/rtc","/dev/hpet",
    "/dev/vfio/vfio","/dev/vfio/0"
]
```

**Comment by tmakatos** [comment]
Great, I'll add this information to the Troubleshooting section of our README.

**Comment by tmakatos** [comment]
Reopening to improve documentation.

**Comment by yuvalk** [comment]
that, and udev rule for permissions on /dev/vfio/* to qemu:kvm

**Comment by tmakatos** [comment]
We've switched to vfio-user and have dropped muser.ko.
