### ISSUE TITLE
vfio-user: function set_version() to process VFIO_USER_VERSION socket message should work with NON_BLOCK mode

### ISSUE THREAD

**Issue by changpe1** [nutanix/muser#60]
The Unix domain socket is set in NON_BLOCK mode, the function should retry until got a valid response from client for the first message on branch vfio-user

**Comment by swapnili** [comment]
Fixed the issue, can you please pull and retest.
Thanks

**Comment by changpe1** [comment]
thanks, the issue is fixed.
