### ISSUE TITLE
remove kernel module

### ISSUE THREAD

**Issue by tmakatos** [nutanix/muser#67]
Can reinstate if needed.

**Comment by swapnili** [comment]
IMO we should support both kernel module as well as vfio-user, unless its not a huge effort which I think it isn't. Instead of totally removing it now and then reinstate later.

**Comment by tmakatos** [comment]
The problem is that we have to convert `vfio-user` requests to `muser_cmd` requests, which is unneccessary. We should send to the kmod the same type of requests. Otherwise we'll have to rewrite the communication between libmuser and the kmod to use `vfio-user` only. In either case it's extra work and we'd better focus on other parts of libmuser. If we remove the kmod now and at some point decide to reinstate it, we can rewrite the interface then. @jlevon thought?

**Comment by jlevon** [comment]
In terms of pros and cons of removing muser.ko and related, we have for pros:

- we can drop all vfio-user->muser_cmd translation code in libmuser
- we don't need to think about rewriting muser.ko/ioctls for vfio-user instead
- we don't need to do further muser.ko development to reflect new vfio-user changes
- we can drop the ko code, build system, etc.
- we don't need to think about ongoing muser.ko regression testing, integration, etc.

And for cons:

- we no longer have a way of keeping the transport layer "honest" if we have only vfio-user-socket as its only implementation
- if others find a use for muser.ko we have no way to support them
- if we decide to bring back muser.ko ourselves for whatever reason, we will more less have to start completely from scratch

Does that sound about right? Is there something else?

**Comment by tmakatos** [comment]
I think you've covered everything.

**Comment by tmakatos** [comment]
Have we reached a conclusion?

**Comment by jlevon** [comment]
So my feeling is that if we wanted to keep muser.ko we'd want to do all the work to remove the need for the vfio-user<->muser_cmd translation as @tmakatos mentions. In addition, move all the module transport code out of the way in a separate file. We also would need to figure out a way to regression test this code.

I'm not sure that's a good use of our time, though. I think this is something we could look at if we needed/wanted to use the module again, and it makes more sense right now to retire that code. (We should put it on a named branch for reference.)

**Comment by swapnili** [comment]
Yes if there is no possibility of anyone using muser.ko in future then its better to remove this code now instead of maintaining it.
